pull_request_rules:
  - name: automatically merge scala-steward's PRs
    conditions:
      - author=scala-steward
      - check-success=Continuous Integratio
      - body~=labels:.*semver-patch
    actions:
      merge:
        method: merge
