language: scala
scala:
  - 2.11.12
  - 2.12.7
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
script:
  - sbt ++$TRAVIS_SCALA_VERSION test
after_success:
  - bash <(curl -s https://codecov.io/bash)
